# Generated by Django 5.2.10 on 2026-01-30 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShortURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("originalUrl", models.URLField()),
                (
                    "shortKey",
                    models.CharField(blank=True, max_length=10, null=True, unique=True),
                ),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("clickCount", models.PositiveIntegerField(default=0)),
                ("isActive", models.BooleanField(default=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
