# Generated by Django 5.2.10 on 2026-01-31 14:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shortener", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="shorturl",
            constraint=models.UniqueConstraint(
                condition=models.Q(("isActive", True)),
                fields=("user", "originalUrl"),
                name="unique_active_url_per_user",
            ),
        ),
    ]
